name: CI/CD
run-name: Build Images
on: [push]
jobs:
  Build-Images:
    runs-on: ubuntu-latest
    env:
      VITE_SUPABASE_URL: ${{secrets.VITE_SUPABASE_URL}}
      VITE_SUPABASE_ANON_KEY: ${{secrets.VITE_SUPABASE_ANON_KEY}}
    steps:
      - name: checking out code
        uses: actions/checkout@v5
      - name: build image
        run: docker build . -t git.workshop.bteklabs.com/dapruk/greeter-app-cik:latest
      - name: login to docker
        run: echo ${{secrets.BTEK_GIT_DEPLOYMENT_TOKEN}} | docker login --username dapruk --password-stdin git.workshop.bteklabs.com
      - name: push image to registry
        run: docker push git.workshop.bteklabs.com/dapruk/greeter-app-cik:latest
